<html>
  <head>
		<meta charset="utf-8" />
		<title>Circuito Social</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" href="../../public/css/style.css" />
		

	</head>
<body>
    

  <div class="container" >
    <div class="d-flex justify-content-center mt-5">
      <div class="card" style="width: 36rem;">
        <div class="card-body" id="cont">

          <div class="d-flex justify-content-center">
            <img class="logo" src="public/img/placa-de-circuito.png"/>
          </div>

          <div class="row">
            <div class="col">
              <h2>Crie sua conta</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              
              <form action="/registrar" method="post">
                <div class="form-group">
                  <input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control" placeholder="Nome">
                </div>
                
                <div class="form-group">
                  <input type="text" value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
                </div>

                <div class="form-group">
                  <input type="password" value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Senha">
                </div>
                
                <div class="mt-4 mb-4">
                  <small class="form-text">
                    Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                  </small>
                </div>
                <button type="submit" class="btn  btn-block">Inscrever-se</button>

                <?php if($this->view->erroCadastro) { ?>

                  <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>

                <?php } ?>
              </form>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</body>
</html>

